name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 2 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8a9aa1d481ebe16666366bd9ef00bf33
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Update Daily Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GIST_ID_DAILY: ${{ secrets.GIST_ID_DAILY }}
        run: python sync_daily.py
